- dump-extensions/openpower-dumps/dump_manager_hardware.cpp
- dump-extensions/openpower-dumps/dump_manager_hostboot.cpp
- dump-extensions/openpower-dumps/dump_manager_resource.cpp
- dump-extensions/openpower-dumps/dump_manager_system.cpp
- dump-extensions/openpower-dumps/op_dump_util.cpp
- dump-extensions/openpower-dumps/op_dump_util.hpp
Review link: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/46085
Add support for system dump policy, here system dump
refers to all OpenPOWER dumps, since all dumps from
host subsystems on OpenPOWER systems are known as system dumps.
The currently supported policy is dump enable. The dump will be
created only if the policy is enabled, if the dump is not
enabled, a dump disabled error will be returned.
If the settings service is not available, considering as
the dump is enabled.
Tests:
- Create a dump with policy enabled
busctl --verbose call xyz.openbmc_project.Settings /xyz/openbmc_project/dump/system_dump_policy org.freedesktop.DBus.Properties Get ss "xyz.openbmc_project.Object.Enable" "Enabled"
MESSAGE "v" {
VARIANT "b" {
BOOLEAN true;
};
};
busctl --verbose …
> OpenPOWER: Add support for OpenPOWER dump policy

- bmc_dump_entry.hpp
- dump-extensions/openpower-dumps/dump_manager_resource.cpp
- dump-extensions/openpower-dumps/dump_manager_system.cpp
- dump-extensions/openpower-dumps/resource_dump_entry.hpp
- dump-extensions/openpower-dumps/system_dump_entry.hpp
- dump_manager_bmc.cpp
- dump_manager_bmc.hpp
This new interface "GeneratedBy" will be implemented
by all the dump entry dbus objects that can be user-
initiated. It contains a property "GeneratorId" which
stores the unique id of the user that has initiated
the dump.
The dbus interface change for the same is at:
https://github.com/ibm-openbmc/phosphor-dbus-interfaces/pull/26/
The design document is at:
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/47446/
The gerrit change is at:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/48337
Tested By:
1.  busctl call xyz.openbmc_project.Dump.Manager /xyz/openbmc_project/dump/bmc xyz.openbmc_project.Dump.Create CreateDump a{sv} 1 "xyz.openbmc_project.Dump.Create.CreateParameters.GeneratorId" s "9iu0ojsx"
o "/xyz/openbmc_project/dump/bmc/entry/2"
* busctl …
> Implement GeneratedBy interface in dump entry dbus obj

- tools/dreport.d/ibm.d/gendumpheader
Change:
-Adding dump creator id i.e. 0x01 for BMC dump,
it is required to know the dump was created on
BMC platform.
Tested:
-Can see the byte getting reflected in header.
Signed-off-by: Chirag Sharma <chirshar@in.ibm.com>
> opdreport: Adding dump creator in header

- dump-extensions/openpower-dumps/dump-extensions.cpp
- dump-extensions/openpower-dumps/dump_manager_hostdump.hpp
- dump-extensions/openpower-dumps/meson.build
- dump_manager.hpp
- dump_manager_bmcstored.hpp
- meson_options.txt
Host dump ids need to be started from certain numbers
this commit adds the starting if for each type of dumps
Hardare dump: Starting ID - 0
Hostboot dump: Starting ID - 20000001
SBE dump: Starting ID - 30000001
Change-Id: I26945184c727e70fb9f543eaa7c2266a650b2793
> Update host dump ids

- dump-extensions/openpower-dumps/system_dump_entry.cpp
The check for host running was added for the
operations on the dumps stored in the host
but in the case of request for offload The system dump
is ready to offload as soon as it is ready in the host.
The state of the host in the BMC may not be updated by
then, so it is not reliable to depend on the host state
in the BMC and if the host is not ready there will be an
error from PLDM.
This commit is for removing the host running check before
sending the initiate offload request to host. The check
for other operations like delete or initiate will not
be impacted
Review link: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/50239
Change-Id: I665485c7605b54fe4f361ec73e2bff9bba87c49e
> Remove host running check for system dump

- dump-extensions/openpower-dumps/clear_hostdumps_poweroff.service
- dump-extensions/openpower-dumps/dump_manager_resource.cpp
- dump-extensions/openpower-dumps/dump_manager_system.cpp
- dump-extensions/openpower-dumps/meson.build
- meson.build
Following fixes are added
1. OpenPOWER: Clear system and resource dump entries while powering off
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/43125
2. Allow user initiated dumps even when policy is disabled
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/49781
> Fixes for dump manager 

- dump-extensions/openpower-dumps/dump_manager_resource.cpp
- dump-extensions/openpower-dumps/dump_manager_system.cpp
- dump_entry.hpp
50815: Add method to get dump id | https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/50815
50817: Ignore already reported resource dump | https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/50817
50818: Ignore dupliate system dump entry | https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/50818
> Fixes for avoding duplicate host stored dumps

- dump-extensions/openpower-dumps/resource_dump_entry.cpp
- dump-extensions/openpower-dumps/system_dump_entry.cpp
- host-transport-extensions/pldm/oem/ibm/pldm_oem_cmds.cpp
Do not wait for a response deleting host dump
The resource dump delete is long-running operation with
dbus call to PLDM for instance id, making it inside a
dbus call will end up timeouts when PLDM tries to
access dump manager. To avoid dead-locks dump manager
will not be waiting for a response after a delete
operation
Testing:
Create system dump and delete the dump
Create 10 resource dumps and delete them one by one
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/50884/4
50922: Add additional trace to host dump operations | https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/50922
> Fix for resource dump delete

- dump-extensions/openpower-dumps/resource_dump_entry.cpp
- dump-extensions/openpower-dumps/system_dump_entry.cpp
Changes:
-Deleting the serialization files of system and resource dumps,
which are used to restore the dbus entries, when delete
entry operation is called need to delete the files from the path,
so that the entries don't get populate again.
Tested:
-Created resource and system dump, this operation creates serial
files for respective dumps. After issuing delete operation, can see
the files from serial path is getting deleted.
Gerrit link: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/51513
Signed-off-by: Chirag Sharma <chirshar@in.ibm.com>
Change-Id: I4ee7accda3eaf4a8c8641739153478ddd97f6c84
> openPower: Removing serial files during delete operation

- dump-extensions/openpower-dumps/clear_hostdumps_poweroff.service
- tools/dreport.d/include.d/functions
- tools/dreport.d/plugins.d/dmesginfo
- tools/dreport.d/plugins.d/pldmflightrecorder
43125: OpenPOWER: Clear system and resource dump entries while powering off | https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/43125
51516: OpenPOWER: Do not delete dump entries during mp reboot | https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/51516
dreport: fix missing log messages related to skipping copy https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/51305
dreport: fix symlinks copy https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/51306/
dreport: Added pldmflightrecorder plugin https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/51308/
dreport: Added dmesginfo plugin https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/51308/
> Updates to dreport and host dump clear

- tools/dreport.d/ibm.d/gendumpinfo
Change:
- Due to syntax issue, unwanted traces were seen in journal
during dump packing of hostdumps.
Tested:
- Post fixing the syntax issue. Not seeing unwanted traces in
the journal.
Gerrit Link: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/51634
Change-Id: Ibbace2d825fd10ed92a9dcaaf6d6ad67b5f207c6
Signed-off-by: Chirag Sharma <chirshar@in.ibm.com>
> opdreport: Fix to remove unwanted entries in journal

- dump-extensions/openpower-dumps/resource_dump_entry.cpp
- host-transport-extensions/pldm/oem/ibm/pldm_oem_cmds.cpp
Currently dump manager is using pldm_send_recv which is
a blocking call and if the host is not responding
dump manager will hang to avoid this using pldm_send
which is a non-blocking call.
Tests:
Send message while host is down and dump manager is
non hung.
Change-Id: Ie90e217325da4c8778c7527afcd453a8fdce02c8
> Use non blocking call for host dump offload request

- dump-extensions/openpower-dumps/dump_manager_system.cpp
In any case if host is reporting the same system entry
twice, ignore alreadsy reported entry
Tests:
Create a disruptive system dump and offload
Create a non-disruptive system dump and offload
Additional minor fix, a return was missing
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/50818/4..5/dump-extensions/openpower-dumps/dump_manager_system.cpp
Change-Id: I31d92df43476a19880d084a68e5db17c5207bd81
> Ignore dupliate system dump entry

- dump-extensions/openpower-dumps/clear_hostdumps_poweroff.service
- dump-extensions/openpower-dumps/dump_manager_resource.cpp
- dump-extensions/openpower-dumps/op_dump_util.cpp
- dump-extensions/openpower-dumps/op_dump_util.hpp
- dump-extensions/openpower-dumps/system_dump_entry.cpp
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/51797 Do not remove InProgress system dump entry during mp reboot
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/51805 Password is not mandatory for resource dump
> Host dump fixes

- dump_offload.cpp
Currently one sec timeout for select() call may not be enough
Intermittently noticed that when bmcweb busy with too many
D-bus operations, socket operations from bmcweb may be delayed.
To address this issue, increasing select() timeout to 5 seconds.
This PR fixes https://w3.rchland.ibm.com/projects/bestquest/?verb=view&defect=SW547774
Tested by:
Few iterations of BMC dump offload
> Dump Offload: Increase select() timeout

- dump-extensions/openpower-dumps/host_dump_entry.hpp
Without this change we get a compile error
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>
> use templated object for sdbusplus emit

- bmcstored_dump_entry.cpp
- dump-extensions/openpower-dumps/resource_dump_entry.cpp
- dump-extensions/openpower-dumps/system_dump_entry.cpp
- dump_manager_main.cpp
There was a duplicate name request in the dump manager
main, may be due to a merge issue.
> Remove duplicate name request

- dump_manager_bmcstored.cpp
- meson.build
- meson_options.txt
Current code is assuming the dump filename is in epoch
but there are cases the timestamp is human readable
format. Add support for such timestamps to convert to
epoch and as the dump time.
Test:
The time is correct now
DICT_ENTRY "sa{sv}" {
STRING "xyz.openbmc_project.Time.EpochTime";
ARRAY "{sv}" {
DICT_ENTRY "sv" {
STRING "Elapsed";
VARIANT "t" {
UINT64 1651592238000000;
};
};
};
Change-Id: Iedbc794f71c09d0a3d515412aa93ed3062302090
> Support for human readable timestamp in dump filename

- bmcstored_dump_entry.hpp
- dump-extensions/openpower-dumps/resource_dump_entry.cpp
- dump-extensions/openpower-dumps/system_dump_entry.cpp
53775: Reset the offload URI after offload complete | https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/53775
53769: OpenPower: Return unvailable if any error in deleting host dump | https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/53769
> Fix for returning error during dbus timeout in host stored dumps

- tools/dreport.d/openpower.d/plugins.d/cfam
- tools/dreport.d/plugins.d/journalpretty
Following changes are done
1) Execute jounalctlpretty plugin as part of rmoops dump generation
2) Add register details for CFAM plugin and also add new BMC SBE state register
CQ: SW551093
Signed-off-by: Marri Devender Rao <devenrao@in.ibm.com>
Change-Id: I1642005e842b08767d052a4f700fe2418b5c0c88
> dreport: collect journal pretty for rmoops dump and add additional details to cfam plugin

- dump-extensions/openpower-dumps/dump_manager_resource.cpp
- dump-extensions/openpower-dumps/dump_manager_system.cpp
- host-transport-extensions/pldm/common/pldm_utils.cpp
Currently resource and system dumps storing the time in
seconds which is not correct according to D-Bus spec
fixig it
Change-Id: Ia789cd51f14a18676f6873625727b22bab14ace4
> Time elapsed should be in micro seconds

- dump-extensions/openpower-dumps/dump_manager_resource.hpp
- dump-extensions/openpower-dumps/dump_manager_system.hpp
- dump_manager.hpp
- dump_manager_bmc.cpp
- dump_manager_bmc.hpp
- dump_manager_bmcstored.hpp
- dump_manager_main.cpp
If dump manager crashes core file will be generated but core dump
will not be created as the dump service that creates core dump
is taking a reset.
Now modified to check for core files at the start of the dump service
and capture them in core dump.
https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/54041
CQ:SW551555
> Check for core files and create core dump during startup of dump service

- tools/dreport.d/openpower.d/plugins.d/guardlist
Guard tool looks for device tree file which is set by enviroment
variable to parse the guard records from the guard partition.
As the device tree location was not found guard tool was writing default
dummy data to the guard file.
https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/54426
Tested:
[Guard list]
ID | ERROR | Type | Path
00000001 | 00000000 | manual | physical:sys-0/node-0/proc-1
Signed-off-by: Marri Devender Rao <devenrao@in.ibm.com>
Change-Id: I74b1720ce8c7140a59e00d35ac45ac8a7c020e53
> openpower:dreport - guard list data not captured properly in BMC dump

- tools/dreport.d/ibm.d/gendumpheader
Change:
-Populating dump identifier in dump header.
Tested:
Post change can see the dump identifier in dump header.
Signed-off-by: Chirag Sharma <chirshar@in.ibm.com>
Change-Id: Idcb1b2c20633ccdd9bb2b3cd763b39cbf945c91f
Gerrit link:- https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/54152
> opdreport: Adding dump identifier

- bmcstored_dump_entry.cpp
- bmcstored_dump_entry.hpp
- dump-extensions/openpower-dumps/dump_manager_hostdump.hpp
- dump_manager_bmc.cpp
- dump_manager_bmc.hpp
- dump_manager_bmcstored.hpp
- meson.build
- subprojects/sdeventplus.wrap
For every dump generated an "anon_inode:[pidfd]" entry is created for the associated process and the same is not released. When the number of inode entries reach the maximum count dump request will fail and the dump service takes a reset with a core dump.
When a dump is requested a child process is spawned to perform dump collection. Parent process waits on the child process completion using sd-event-add-child systemd call. sd-event-add-child adds an inode entry which needs to be released during the callback method called after child process exit using unref but the same is not done.
Now switching to sdeventplus::source::Child wrapper class for sd-event-add-child which takes care of releasing the inode fd.
Tested:
Without the fix for the 3 dumps created noticed 3 anon_inode:[pidfd]
are …
> sdevent - inode entry created during dump generation is not released

- tools/dreport.d/plugins.d/emconfig
Add /var/configuration/system.json to BMC dumps as em-system.json.  This
file contains a JSON representation of the objects that entity-manager
puts on D-Bus and can be used to debug problems when entity-manager
crashes.
Tested:
~/dumps/BMCDUMP.13BE960.00000000.20220802172737_out/archive$ ls -l em-system.json
-rw-r--r--. 1 spinler spinler 10688 Aug  2 12:27 em-system.json
Signed-off-by: Matt Spinler <spinler@us.ibm.com>
Change-Id: Icc4e38e9594b578b83b65a23af8da67e514572c2
> dreport: Add entity-manager's system.json to dump

- tools/dreport.d/plugins.d/fanmondump
Send the USR1 signal to phosphor-fan-monitor to collect its dump data as part of a BMC dump.
Tested:
~/BMCDUMP.139F210.00000041.20220908143628_out/archive$ cat fan_monitor_dump.json {
"logs": [],
"sensors": {
"sensors": {
"/xyz/openbmc_project/sensors/fan_tach/fan0_0": {
"functional": true,
"in_range": true,
"present": true,
"prev_tachs": "[11904,11867,11904,11904,11867,11904,11867,11904]",
"prev_targets": "[18000,0,0,0,0,0,0,0]",
"tach": 11904.0,
"target": 18000,
"ticks": 0
},
...
}
Signed-off-by: Matt Spinler <spinler@us.ibm.com>
Change-Id: I1173a38a755edff14ee0d418ec29ac0c583a790f
> dreport: Add phosphor-fan-monitor data to dump

- tools/dreport.d/ibm.d/gendumpheader
opdreport : fix driver as unknown error when parsing scs dump header
The get_dump_id function has been modified to handle the odd dump ID size so
that id doesn't add any extra byte
The Problem:
00000020  31 33 39 46 32 33 30 2e  30 30 30 30 30 30 30 31  |139F230.00000001| <-------Dump ID is 1 which is the entry ID as well
000000e0  00 00 00 00 01 02 21 04  00 00 00 00 00 00 63 96  |......!.......c.| <--------Dump ID comes as 00 00 00 00 01 which is same as previous with an extra byte added
The solution:
00000020  31 33 39 46 32 33 30 2e  30 30 30 30 30 30 30 39  |139F230.00000009| <-------Dump ID is 9 which is the entry ID as well
000000e0  00 00 00 09 02 21 04 00  00 00 00 00 00 63 8d 02  |.....!.......c..| <--------Dump ID comes as 00 00 00 09 which is correct 4 bytes value without an …
> opdreport : fix driver as unknown error when parsing scs dump header

- dump_utils.cpp
PCI init starts once the host is started and the resource dump or system dump can be initiated at this stage. There are usecase where host is stuck at this stage so collecting a system dump or resource dump is critical for the debug.
Test: Set the state and initiated the resource dump
Change-Id: I8ba7246fe84c146c104644b18507cd217db42d18
> OpenPOWER: Add PCIInit also as host running state

- dump_manager_bmc.cpp
- tools/dreport.d/ibm.d/gendumpheader
Phosphor-dump-manager : Handled quota exceeded exception
BMC goes into Quiesced state due to the crashing of Phosphor Dump manager for
not being able to handle the exception thrown while capturing core dumps if the
disk quota is full
> Phosphor dump manager : Crashed for quota exceeded error

- tools/dreport.d/plugins.d/auditlog
Add /var/log/audit/audit.log to BMC dumps as audit-log.log. This file contains a log of the events that occurred and who initiated them.
Tested:
~/Code/dumps/2/BMCDUMP.SIMP10R.00000002.20220919155900_out/archive$ ls -la audit-log.log 
-rw-r--r-- 1 zamiseck zamiseck 3993 Sep 19 10:59 audit-log.log
> dreport: Add audit.log Data to Dump

- tools/dreport.d/ibm.d/plugins.d/badpel
The last invalid/corrupt PEL the host sent down to the BMC is saved in /var/lib/phosphor-logging/extensions/pels/badPEL.  Save it in a dump if it exists so we can get the contents when it happens in the field.
Tested:
~/BMCDUMP.SIMP10R.00000000.20221012205429_out/archive$ ls -l badPEL -rw-r--r--. 1 spinler spinler 5599 Oct 12 15:54 badPEL
Signed-off-by: Matt Spinler <spinler@us.ibm.com>
Change-Id: Id6052d5c4c052860e978314e541d4a1b978ee615
> openpower:dreport: Save badPEL file in dump

- bmc_dump_entry.hpp
- dump-extensions/openpower-dumps/dump_manager_resource.cpp
- dump-extensions/openpower-dumps/dump_manager_system.cpp
- dump-extensions/openpower-dumps/resource_dump_entry.hpp
- dump-extensions/openpower-dumps/system_dump_entry.hpp
- dump_entry.hpp
- dump_manager.hpp
- dump_manager_bmc.cpp
- dump_manager_bmc.hpp
- dump_utils.hpp
This new interface "OriginatedBy" will be implemented by all the dump entry dbus objects. It contains a property "OriginatorId" which stores the unique id of the user that has initiated the dump. The unique id in this case is a string that contains the ip address of the client that initiated the dump.
The dbus interface change for the same is at:
[1] https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/47057
Tested By:
[1] busctl call xyz.openbmc_project.Dump.Manager /xyz/openbmc_project/dump/bmc xyz.openbmc_project.Dump.Create CreateDump a{sv} 2 "xyz.openbmc_project.Dump.Create.CreateParameters.OriginatorId" s "<unique-id>" "xyz.openbmc_project.Dump.Create.CreateParameters.OriginatorType" s "xyz.openbmc_project.Common.OriginatedBy.OriginatorTypes.Client" o …
> Implement OriginatedBy interface in dump entry dbus obj

- bmcstored_dump_entry.cpp
- dump-extensions/openpower-dumps/resource_dump_entry.cpp
- dump-extensions/openpower-dumps/system_dump_entry.cpp
- dump_utils.cpp
- dump_utils.hpp
Addition of PEL message method for dump delete/offload
Adding a createPEL method which will log PEL messages.
This method has PEL severity as Informational by default
unless mentioned otherwise
Change-Id: b4e1622407fa9aa372fe0f20f73509cb376f90c5
Signed-off-by: swarnendu.roy.chowdhury@ibm.com
> Addition of PEL message method for dump delete/offload

- tools/dreport.d/dreport
```
With recent beautysh updates dreport -type option is broken
with below error
"Invalid -type, Only summary log is available"
Tested:
verified dreport -v -t user.
Change-Id: Id3cc1d1165acc4e10b94268b91df448758cdd428
Signed-off-by: Jayanth Othayoth <ojayanth@in.ibm.com>
```
> 1050: dreport: fix invalid -type related error

- dump_utils.cpp
This commit adds SystemSetup state as valid state to allow host dump collection
SystemSetup is a BootProgress that indicates the host is booted, needs to allow host
dump collection
> Add SystemSetup state to allow dump collection

- dump_utils.cpp
Adding an utility method createPEL to help to log PEL messages for dump delete/invalidation. This method has PEL severity as Informational by default unless mentioned otherwise.
***No functional changes than earlier commit https://github.com/ibm-openbmc/phosphor-debug-collector/pull/92, only the log level enum has been changed so no further testing is required***
Upstream has been updated also in accordence https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/53547
Change-Id: 2f9b01a0e0cee906e9549acf160b9456ae48e87d
Signed-off-by: Swarnendu Roy Chowdhury <swarnendu.roy.chowdhury@ibm.com>
> Add utility method to create PEL for dump invalidation

- tools/dreport.d/plugins.d/auditlog
Gather as many audit log files as exist from the /var/log/audit directory.
> Audit Log: Correct location for gathering audit log files.

- bmc_dump_entry.hpp
- bmcstored_dump_entry.cpp
A block code was not removed when chery picking following commit
53547: Add informational PEL for dump delete or offload https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/53547
> Fix the merge issue from master

- dump_manager_bmcstored.cpp
- meson_options.txt
- tools/dreport.d/ibm.d/plugins.d/faultlog
63094: OpenPOWER: Fix the system dump filename format | https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/63094
63095: OpenPOWER: Set the device tree path in script | https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/63095
> Fixes for NAG

- meson_options.txt
There was a duplicate SYS_DUMP_FILENAME_REGEX and
BMC_DUMP_FILENAME_REGEX which might came from a
wrong merge, removing the duplicate one
> Remove the duplicate DUMP_FILENAME_REGEX from meson_options.txt

- tools/dreport.d/dreport
- tools/dreport.d/ibm.d/gendumpheader
- tools/dreport.d/ibm.d/package
Change:
For dump type faultdata the name in the header shpuld be NAGDUMP, so that HMC can recognize the type of dump from header.
Tested:
Post changes can see header is getting updated with name NAGDUMP.
> dreport: Adding NAG DUMP support in header

- tools/dreport.d/ibm.d/gendumpheader
- tools/dreport.d/openpower.d/opdreport
Changes:
Added check for errorlog, so that during packaging we don't write extra bytes in header.
Corrected the content_type to fetch correct dump id.
Tested:
Post changes makedump tool is able to extract the platform dumps.
Change-Id: Ib6116d0a2660c25da8e06adc020db4632bf4d1bc
> opdreport: Added check for errorlog

- bmcstored_dump_entry.cpp
- bmcstored_dump_entry.hpp
There were some merge conflicts with bmcstores_dump_entry.cpp - it was accidentally overwritten. A modification from commit 1030 wasn't pushed to the master branch. To resolve this, I've updated the master branch and pulled the changes into commit 1050.
Testing procedures:
A BMC dump was successfully created and offloaded.
Validated that deletion is disabled during offloading.
Confirmed that multiple simultaneous offloads are prevented.
Created a sizable 400MB dummy dump file to test offload. With the implemented changes, the offload was completed in 1 minute. Without these updates, the offload would time out after 30 seconds.
> Dump offload fixes

- tools/dreport.d/ibm.d/gendumpheader
Change:
The change involves adding PEL information to the dump header for checkstop and elog dump types in the dreport utility. After implementing the changes, the PEL ID is successfully included in the dump header.
Tested:
The changes have been tested, and the PEL ID is now properly added to the dump header as intended.
> dreport: Added PEL to the BMC dump header

- .shellcheck-ignore
- ffdc
- tools/dreport.d/plugins.d/traceevents
Add the output of the linux trace buffer to user dumps, with lowest priority since the file can be large (~10MB).
> Add linux trace events

- dump-extensions/openpower-dumps/dump_manager_resource.hpp
- dump-extensions/openpower-dumps/dump_manager_system.hpp
- dump_manager.hpp
- dump_manager_bmc.cpp
- dump_manager_bmc.hpp
- dump_manager_bmcstored.hpp
- dump_manager_faultlog.hpp
- dump_manager_main.cpp
If dump manager crashes core file will be generated but core dump will not be created as the dump service that creates core dump is taking a reset.
Now modified to check for core files at the start of the dump service and capture them in core dump.
Tested:
May 27 10:51:32 ever6bmc systemd-coredump[11886]: [🡕] Process 11697 (phosphor-dump-m) of user 0 dumped core.
May 27 10:51:32 ever6bmc systemd[1]: systemd-coredump@18-11885-0.service: Deactivated successfully.
May 27 10:51:33 ever6bmc phosphor-dump-monitor[11715]: Failed to create dump: sd_bus_call noreply: org.freedesktop.DBus.Error.NoReply: Remote peer disconnected
May 27 10:51:33 ever6bmc systemd[1]: xyz.openbmc_project.Dump.Manager.service: Main process exited, code=dumped, status=11/SEGV
May 27 10:51:33 ever6bmc systemd[1]: …
> create core dump if core files exit during startup (#59)

- bmc_dump_entry.hpp
- bmcstored_dump_entry.hpp
- dump-extensions/openpower-dumps/hardware_dump_entry.hpp
- dump-extensions/openpower-dumps/host_dump_entry.hpp
- dump-extensions/openpower-dumps/resource_dump_entry.hpp
- dump-extensions/openpower-dumps/sbe_dump_entry.hpp
- dump-extensions/openpower-dumps/system_dump_entry.hpp
The deletion of the dump objects emits InterfacesRemoved signal, but the interfaces removed in the signal does not contain the interfaces defined in the base class phosphor::dump::Entry:
```
xyz.openbmc_project.Common.OriginatedBy
xyz.openbmc_project.Common.Progress
xyz.openbmc_project.Dump.Entry
xyz.openbmc_project.Object.Delete
xyz.openbmc_project.Time.EpochTime
```
This results in the mapper still keeping the objects even if the object is removed from DBus, and it becomes inconsistent between the DBus objects and mapper.
Adjust the inheritance sequence, so that in destruction, emit_object_removed() is called when all the interfaces are there, so that all the interfaces could be included in the signal.
Without this change, the destructor sequence is (Taking BMCEntry as example):
1. …
> Correct the timing of emit_object_added

- bmc_dump_entry.hpp
- bmcstored_dump_entry.hpp
- dump-extensions/openpower-dumps/hardware_dump_entry.hpp
- dump-extensions/openpower-dumps/host_dump_entry.hpp
- dump-extensions/openpower-dumps/sbe_dump_entry.hpp
When the bmc dump is deleted, it emits two Interfaces Removed signal on the bmc dump entry object.
bmc_stored::Entry inherits phosphor_dump_entry and other interfaces which are inherited from sdbusplus object class who emit Interfaces Remvoved signal. bm_stored::Entry is further inherited in other classes. So adding a virtual inheritance resolved the duplicate signals emitted.
Tested and found only one InterfacesRemoved signal emitted on bmc dump deletion. And tested the other dump creation and deletion and it works as expected.
> Fix duplicate InterfacesRemoved signal

- dump-extensions/openpower-dumps/dump_manager_hostdump.hpp
An additional local variable was preventing the correct dump type to be passed to the function extracting the failing unit id.
Tested:
busctl --verbose call xyz.openbmc_project.Dump.Manager /xyz/openbmc_project/dump/sbe xyz.openbmc_project.Dump.Create CreateDump a{sv} 2 "com.ibm.Dump.Create.CreateParameters.ErrorLogId" t 0xDEADBEEF "com.ibm.Dump.Create.CreateParameters.FailingUnitId" t 0
MESSAGE "o" {
OBJECT_PATH "/xyz/openbmc_project/dump/sbe/entry/30000003";
};
Sep 04 20:48:50 rain104bmc phosphor-dump-manager[2870]: Creating dump with dumpPath(/var/lib/phosphor-debug-collector/sbedump/30000003) id(30000003) available space(102400) eid(deadbeef) dump type(10) failing unit(0)
Sep 04 20:48:50 rain104bmc phosphor-dump-manager[2882]: Collecting SBE dump: …
> Failing unit id was wrong for SBE dumps

- ramoops_manager.cpp
- ramoops_manager.hpp
A ramoops being detected is a critical event for a BMC based system. It indicates the BMC had an unexpected reboot because of a kernel panic. Ensure a log is reported so the user of the system knows to look for a BMC dump with the debug information.
Tested:
- Manually created some files in /var/lib/systemd/pstore/ and ran the ramoops application and verified the expected log was created.
Upstream: https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/67677
Change-Id: Id1162fa0cca72e5dcc8cf59e75bd298d2ddada2e
> ramoops: generate error log when ramoops detected

- dump-extensions/openpower-dumps/dump-extensions.cpp
- dump-extensions/openpower-dumps/meson.build
- dump-extensions/openpower-dumps/op_dump_util.cpp
- dump-extensions/openpower-dumps/op_dump_util.hpp
- meson_options.txt
The memory buffer SBE dump is similar to the dump collected from the processor SBE, but with a different method. This dump is collected during a critical failure on the SBE and contain specific debug data.
This commit provides an interface calling the dump collection so other services can invoke dump collection when there is an SBE failure detected.
> Add support for Memory Buffer SBE dump

- tools/dreport.d/plugins.d/ldapdump
LDAP related detailed data will be collected as part of BMC user initiated Dump.
This commit will add 2 new file:
1. usrmgrldap.log (size: 3.1K)
2. nslcd.log (size: 526B)
Tested By:
Tested by collecting BMC dump.
Change-Id: I09e35379935838c6f06d8604303f16a1febc8d3a
Upstream Commit: https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/68090
> dreport: Added support to collect LDAP config data

- tools/dreport.d/plugins.d/journalpretty
This change was is in our 1020-1040 release but we lost it during our 1050 rebase. Pull back into 1060 and pending must-fix we'll get into 1050 as well.
We can't upstream because systems with smaller flashes do not want this and finding a way to dynamically configure this file is complicated.
> Modify plugin to capture all journal data during elog/core dump

- meson_options.txt
The SBE dumps from processor and OCMB are differentiated with dump ID but presented outside as SBE dumps, keeping the common path for all types of SBE dumps.
Tests:
Created SBE dump 
- Listed
- Offloaded
- Deleted
from both the redfish command and GUI
> Keep common entry path for all SBE dump types

- tools/dreport.d/openpower.d/opdreport
This commit addresses an issue where dump entries erroneously remained in the "InProgress" state when errors occurred during the dump collection or packaging processes. The absence of a status update to "Failed" in such scenarios misled callers about the actual state of the dump.
Tested:
The status got updated when the dump collection failed.
> Fix handling of dump status on collection or packaging failure

- tools/dreport.d/ibm.d/gendumpinfo
Problem: Sometimes start and end time strings of the dumpheader can not be fetched/retrieved from the busctl commands and that leads to failure in makedumptool parsing due to invalid dump header.
Solution: Now if the start and end time strings are coming blank for any reason we are setting them manually with the current date time to avoid wrong dump header.
Test Results:
Before:
phosphor-dump-manager[6158]: date: invalid date '@'
phosphor-dump-manager[6141]: /usr/share/dreport.d/include.d/gendumpinfo:
line 45: [: -eq: unary operator expected
phosphor-dump-manager[6159]: date: invalid date '@'
dumpfile.stats.actualTime = (yamlData['dump-end-time']
- yamlData['dump-start-time']).total_seconds() TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
After: …
> Empty strings issue for start and end time of dump header corrected

- dump-extensions/openpower-dumps/resource_dump_entry.hpp
This commit replaces the 'Password' field with 'UserChallenge' in the Resource dump implementation of xyz.openbmc_project.Dump.Entry.Resource interface.
The 'UserChallenge' is used to verify user authorization against an Access Control List provided through PLDM. This ensures that dump requests are processed only if the user-challenge is validated successfully.
Test:
Successfully built with p10bmc
Change-Id: I1896c4645d1329e47556b8d75fff8cb6aae45945
> OpenPOWER: Replace Password with UserChallenge

- dump-extensions/openpower-dumps/dump_manager_openpower.cpp
- dump-extensions/openpower-dumps/op_dump_util.cpp
- dump-extensions/openpower-dumps/op_dump_util.hpp
- dump_utils.hpp
- meson.build
- meson.options
This commit adds support for customizable BMC dump filenames. IBM systems, for example, require a specific dump name format. It is documented within IBM that all subsystems involved in creating dumps need to follow this specific format. To meet this requirement and accommodate similar ones for other platforms, this commit introduces new meson options. These options allow for the specification of a custom filename format using a regular expression, and for the positions of the dump ID and timestamp within that format. This provides greater flexibility and ensures the dump naming process can be tailored to the platform's requirements.
An important note is that the dreport tool, which packages the dump, should also adapt to the same customizable filename format. Any discrepancy in the dump …
> Support configurable dump filename

- bmc_dump_entry.hpp
- dump-extensions/openpower-dumps/dump_entry_factory.cpp
- dump-extensions/openpower-dumps/dump_entry_factory.hpp
- dump-extensions/openpower-dumps/dump_manager_openpower.cpp
- dump-extensions/openpower-dumps/dump_manager_openpower.hpp
- dump-extensions/openpower-dumps/openpower_dump_entry.hpp
- dump-extensions/openpower-dumps/resource_dump_entry.cpp
- dump-extensions/openpower-dumps/resource_dump_entry.hpp
- dump-extensions/openpower-dumps/system_dump_entry.cpp
- dump-extensions/openpower-dumps/system_dump_entry.hpp
- dump_entry.cpp
- dump_entry.hpp
- dump_manager_bmc.cpp
- dump_manager_bmc.hpp
71728: OpenPOWER: Memory Buffer SBE dump support | https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/71728
71731: Add Serialization Support for Dump Entry Attributes | https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/71731
71732: OpenPOWER: Add serialization support | https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/71732
71733: OpenPOWER: Serialization support for dumps in host memory | https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/71733
> Updates to phosphor-dump-manager

- tools/dreport.d/plugins.d/redundantosrelease
To support additional information, the non booting FW info is added in a separate file along with active/booting FW in the os-release file for all the BMC dumps.
This commit includes the changes to add the redundant or backup FW version name (if present), in a separate file named redundant-os-release file for all the BMC dumps.
Test Results:
cat BMCDUMP.13BE960.0000053.20240510180023/redundant-os-release
REDUNDANT_FW="fw1060.00-16-1060.2420.20240508a (NL1060_042)"
> dreport: Adding redundant FW info in BMC dumps

- tools/dreport.d/dreport
- tools/dreport.d/ibm.d/gendumpheader
- tools/dreport.d/include.d/dcommon
- tools/dreport.d/include.d/functions
There are two parameters available for each dump,
Originator ID and Originator Type. This change
aims to include these fields into the BMC dump
header.
If for any reason either the originator ID or
originator type or both are unavailable then
they are been replaced by their allocated null
bytes.
Test Results:
Tested on generated BMC dumps and verified.
> gendumpheader: Originator details info added

- tools/dreport.d/dreport
- tools/dreport.d/ibm.d/gendumpheader
- tools/dreport.d/include.d/dcommon
- tools/dreport.d/include.d/functions
There is a parameter available for each dump,
Generator ID. This change aims to include this
field into the dump header.
If for any reason the generator ID is unavailable then it is been replaced by their allocated null bytes.
Test Results:
Tested on generated BMC dumps and verified.
> gendumpheader: Generator ID info added

- dump-extensions/openpower-dumps/dump_entry_factory.hpp
Both proc and OCMB SBE dump ids were having same start number it should be 3xxx for proc sbe dump and 4xxx for OCMB SBE dump
> Fix the typo in finding dump id

- tools/dreport.d/include.d/functions
- tools/dreport.d/plugins.d/minfwlevelinfo
- tools/dreport.d/plugins.d/redundantosrelease
It has been requested that while generating BMC dumps it should include redundant F/W information as well as minimum F/W level supported info.
These changes aim to incorporate the above said requests by creating two plugins, namely redundantos release and minfwlevelinfo, under dreport. If, in case the info/s is not available then it logs a related warning in dreportlog file about it.
Test Results:
Tested for both the plugins for both positive and negative cases and found the results as per the expectations.
> dreport: Redundant and Min FW info added

- host-transport-extensions/pldm/oem/ibm/pldm_oem_cmds.cpp
As part of libpldm rebase of one master commit [1], symbolic link of file_io.h is removed, so changing the include path of file_io.h to libpldm/oem/ibm/file_io.h
[1]: https://github.com/ibm-openbmc/libpldm/pull/41/commits/a1efaa2ef3811d900e1c4ab5b5af1933a6286241
> Changing include path of file_io.h to oem/ibm/file_io.h

- tools/dreport.d/include.d/functions
- tools/dreport.d/plugins.d/minfwlevelinfo
- tools/dreport.d/plugins.d/redundantosrelease
It has been requested that while generating BMC dumps it should include minimum F/W level supported info.
These changes aim to incorporate the above said request by creating one plugin, namely minfwlevelinfo, under dreport. If in case the info is not available then it logs a related warning in dreportlog file about it.
Also the redundantosrelease plugin file has been modified because both the plugins, redundantosrelease and minfwlevelinfo use same lines of code almost, and thus, putting that in the functions script we can make them available for both the plugins. And with little bit of pre checks in the related plugins we avoid unnecessary repetitive calls of the same code and dbus invokes.
Test Results:
Tested for both the plugins for both positive and negative cases and found the …
> dreport: Min FW info added

- dump_manager_bmc.cpp
For each dump directory, we create a dbus entry if not present or update it if there is an existing entry. Now, we have .preserve file along with the Dump file in the directory. So, skipping .preserve file and creating an entry for the dump file if exists.
Test Results:
Before:
Sep 17 10:27:05 p10bmc systemd[1]: Starting Phosphor Dump Manager... Sep 17 10:27:05 p10bmc phosphor-dump-manager[6765]: Invalid Dump file name, FILENAME: /var/lib/phosphor-debug-collector/dumps/4/.preserve Sep 17 10:27:05 p10bmc phosphor-dump-manager[6765]: Invalid Dump file name, FILENAME: /var/lib/phosphor-debug-collector/dumps/1/.preserve Sep 17 10:27:05 p10bmc phosphor-dump-manager[6765]: dump_manager_ faultlog restore not implemented
Sep 17 10:27:05 p10bmc systemd[1]: Started Phosphor Dump Manager.
After:
Sep …
> Skip .preserve file while creating a dbus entry

- tools/dreport.d/plugins.d/bmcweb
1) Send SIGUSR1 signal to bmcweb so that it captures session and persistent data to a file
2) Copy the file to the BMC dump package
Tested:
Thu Apr 28 10:04:28 UTC 2022 INFO: Copied BMCWeb current session snapshot data /var/persist/home/root/bmcweb_current_session_snapshot.json Thu Apr 28 10:04:28 UTC 2022 INFO: Copied BMCWeb current session persistent data /var/persist/home/root/bmcweb_persistent_data.json
root@rain104bmc:/tmp/test/obmcdump_00000000_1651140267# ls -lah bmcweb_current_session_snapshot.json
-rw-r--r--    1 root     root         414 Apr 28 10:04
bmcweb_current_session_snapshot.json
root@rain104bmc:/tmp/test/obmcdump_00000000_1651140267# ls -lah
bmcweb_persistent_data.json
-rw-r-----    1 root     root         646 Apr 28 10:04
bmcweb_persistent_data.json
Change-Id: …
> Add bmcweb host and session details to BMC dump

- tools/dreport.d/ibm.d/gendumpheader
Issue 1: When both originator_type and originator_id are empty,
only 4 bytes is being null padded(after 1st if check)
instead of the reserved 36 bytes that was intended for
originator details. This is causing missed padding.
Issue 2: Only originator_type could be valid with originator_id empty,
in which case it is not intended to add either of them,
instead padding of 36 null Byte is the expected outcome.
Fix: If either of originator_id or originator_type is empty, pad 36B.
Test Results: Verified that BMC Dumps are generated with padding.
> gendumpheader: Include both originator details or none in dump header

- dump-extensions/openpower-dumps/meson.build
- dump-extensions/openpower-dumps/yamls/dump_types.yaml
- dump-extensions/openpower-dumps/yamls/meson.build
- meson.build
A fault data dump is a special dump that contains the details stored on the BMC about the faulty components in a system.
This commit enables the fault data dump.
Test Results:
```
root@p10bmc:~# busctl --verbose call xyz.openbmc_project.Dump.Manager /xyz/openbmc_project/dump/bmc xyz.openbmc_project.Dump.Create CreateDump a{sv} 1 "xyz.openbmc_project.Dump.Create.CreateParameters.DumpType" s "xyz.openbmc_project.Dump.Create.DumpType.FaultData"
MESSAGE "o" {
OBJECT_PATH "/xyz/openbmc_project/dump/bmc/entry/26";
};
```
journal:
```
Feb 01 04:56:01 p10bmc phosphor-dump-manager[568]: OriginatorId is not provided
Feb 01 04:56:01 p10bmc phosphor-dump-manager[568]: OriginatorType is not provided. Replacing the string with the default value
Feb 01 04:56:01 p10bmc phosphor-dump-manager[568]: …
```
> OpenPOWER: Add custom dump type

- tools/dreport.d/ibm.d/gendumpheader
- tools/dreport.d/include.d/functions
Issue1: Originator_Id string is not getting extracted properly. Fix to extract Originator_id string correctly.
Issue2: Currently if either of the originator id or type is empty the other is not being included in the dump header. Add either of them even if one is missing.
Test Results:
BMC Dumps initiated from Web-UI
ORIGINATOR_ID EMPTY ORIGINATOR_TYPE = '0'
00000220 ....... |YW30UF15700C0...|
00000230 ....... |................|
ORIGINATOR_ID = 1.2.3.4 ORIGINATOR_TYPE is EMPTY
00000220 ....... |YW30UF15700C....|
00000230 ....... |1.2.3.4.........|
ORIGINATOR_ID = 1.2.3.4 ORIGINATOR_TYPE = '0'
00000220 ....... |YW30UF15700C0...|
00000230 ....... |1.2.3.4.........|
BMC Dump initiated using busctl command
00000220 ....... |YW30UF15700C1...|
00000230 ....... |................|
Verified that …
> gendumpheader: Add originator id & type even if either is missing

- core_manager.cpp
- core_manager.hpp
When Dump manager is unavailable during core dump creation, we miss to create the dump. Adding a timer to re-trigger any failed core dump requests after every 5 minutes to fix this issue.
Test Results:
Feb 07 06:06:12 p10bmc systemd[1]: Started Phosphor Dump core monitor.. Feb 07 06:06:35 p10bmc systemd[1]: Started Process Core Dump (PID 12904
/UID 0).
Feb 07 06:06:36 p10bmc systemd-coredump[12905]: elfutils disabled,
parsing ELF objects not supported
Feb 07 06:06:36 p10bmc systemd-coredump[12905]: [LNK] Process 527
(phosphor-dump-m) of user 0 dumped core.
Feb 07 06:06:36 p10bmc systemd[1]: systemd-coredump@1-12904-0.service:
Deactivated successfully.
Feb 07 06:06:36 p10bmc phosphor-dump-monitor[12900]: Failed to create
dump: sd_bus_call noreply: org.freedesktop.DBus.Error.
NoReply: …
> Add a timer to re-trigger failed core dump requests

- .shellcheck-ignore
- tools/dreport.d/ibm.d/gendumpheader
- tools/dreport.d/plugins.d/emobjects
Collect entity-manager's D-Bus properties.
Tested:
The file and the data are in the dump:
```
~/BMCDUMP.XXXXXXX.00000000.20250226205426_out/archive$ head emobjects.log
MESSAGE "a{oa{sa{sv}}}" {
ARRAY "{oa{sa{sv}}}" {
DICT_ENTRY "oa{sa{sv}}" {
OBJECT_PATH "/xyz/openbmc_project/inventory/system/board/Ingraham_Board";
ARRAY "{sa{sv}}" {
DICT_ENTRY "sa{sv}" {
STRING "org.freedesktop.DBus.Peer";
ARRAY "{sv}" {
};
};
```
> Add entity-manager objects to dump

- tools/dreport.d/plugins.d/auditlog
Rebase 9ef050e Merge pull request #100 from jeaaustx/1050-auditLog
Add all /var/log/audit/audit.log files to BMC dumps. This file contains a log of the events that occurred and who initiated them.
Tested:
Verified audit.log files included in BMC dump.
Commits included:
```
a9c67a0 Audit Log: Allow auditlog plugin to be processed by shellcheck
d7c3038 Audit Log: Correct formatting errors in auditlog plugin
8f33a04 Audit Log: Corrected shellcheck errors in auditlog plugin
5689f30 Audit Log: Correct location for gathering audit log files. (#98)
5be61bf dreport: Add audit.log Data to Dump (#66)
```
> dreport: Add audit.log Data to Dump (#140)

- bmc_dump_entry.hpp
- bmcstored_dump_entry.cpp
- dump-extensions/openpower-dumps/resource_dump_entry.cpp
- dump-extensions/openpower-dumps/system_dump_entry.cpp
- dump_utils.hpp
- meson.build
- meson_options.txt
Currently, there is no distinct PEL for dump offload. When a dump is offloaded from the HMC, it is deleted after the offload, and the user only sees a delete PEL. As a result, users cannot distinguish between a manual dump deletion and a dump offload. To address this, creating a separate offload PEL, enabling users to differentiate between manual dump deletions and dump offloads.
Test Results:
```
Apr 03 10:11:40 p10bmc bmcweb[874]: (2025-04-03 10:11:40) [CRITICAL "dump_offload.hpp":405] INFO: bmc Dump id 2 offload initiated by: 10.231.201.31
Apr 03 10:11:40 p10bmc phosphor-dump-manager[469]: offload started id(2) uri(/tmp/DumpOffloadSockets/bmc_dump_592)
Apr 03 10:11:41 p10bmc phosphor-offload-handler[1762]: Opening File for RW, FILENAME(BMCDUMP.139F230.0000002.20250403101010)
Apr 03 …
```
> Create PEL when a dump is offloaded

- dump-extensions/openpower-dumps/resource_dump_entry.cpp
- dump-extensions/openpower-dumps/system_dump_entry.cpp
Create offload PEL for system/resource dumps to allow differentiation between manual dump deletion and dump offload. This functionality is enabled for BMC and BMC stored dumps in earlier commit.
Tested:
```
Mar 28 09:50:28 rain149bmc phosphor-dump-manager[6350]: Sending request to offload dump id(2), eid(9)
Mar 28 09:50:28 rain149bmc phosphor-dump-manager[6350]: Done. PLDM message, id(2 )RC(0)
Mar 28 09:50:28 rain149bmc pldmd[691]: Hit the object path match for /xyz/openbmc_project/dump/system/entry/1
Mar 28 09:50:28 rain149bmc pldmd[691]: DumpHandler::getOffloadUri path = /xyz/openbmc_project/dump/system/entry/1 fileHandle = 2
Mar 28 09:50:28 rain149bmc pldmd[691]: socketInterface=/tmp/DumpOffloadSockets/system_dump_93
Mar 28 09:50:28 rain149bmc phosphor-log-manager[346]: Created PEL …
```
> Create offload PEL for system and resource dump
