- dump-extensions/openpower-dumps/opdreport
- tools/dreport.d/ibm.d/gendumpinfo
PR details for the same:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/50229/
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/50777/
> Adding info.yaml file in host dumps

- dump-extensions/openpower-dumps/dump-extensions.cpp
- dump-extensions/openpower-dumps/dump_manager_resource.cpp
- dump-extensions/openpower-dumps/dump_manager_resource.hpp
- dump-extensions/openpower-dumps/dump_manager_system.cpp
- dump-extensions/openpower-dumps/dump_manager_system.hpp
- dump-extensions/openpower-dumps/meson.build
- dump-extensions/openpower-dumps/resource_dump_entry.cpp
- dump-extensions/openpower-dumps/resource_dump_entry.hpp
- dump-extensions/openpower-dumps/resource_dump_serialize.cpp
- dump-extensions/openpower-dumps/resource_dump_serialize.hpp
- dump-extensions/openpower-dumps/system_dump_entry.cpp
- dump-extensions/openpower-dumps/system_dump_entry.hpp
- dump-extensions/openpower-dumps/system_dump_serialize.cpp
- dump-extensions/openpower-dumps/system_dump_serialize.hpp
- dump_manager_main.cpp
- meson_options.txt
Gerrit links for the same is mentioned below:-
System dump: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/47088
Resource dump: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/47234
> OpenPOWER: Serialization of platform dumps

- dump_manager_bmc.cpp
1) We are forking a process and initiating dump process, in the
mean time if another dump request comes another child process will
be forked and so on causing N of dumps collected in parallel. Adding
restriction to collect one dump at a time, as the contents of the
dump will not vary if collected multiple times at the same time.
2) System is running out of memory as N no of dumps are collected
in the forked child processes. The check to see if space is available
is missed as it done prior to dump collection in the parent process
when the dump D-Bus entry is created.
3) Modified to return Not allowed error if user initiated dump
requests received while one is in progress.
Tested:
phosphor-dump-manager[21276]: Adding Dump Header :/usr/share/dreport.d/include.d/gendumpheader …
> Don't allow new user-requested BMC dump while a user dump is in progress

- dump-extensions/openpower-dumps/dump_manager_hostdump.hpp
- dump-extensions/openpower-dumps/meson.build
- dump-extensions/openpower-dumps/opdreport
- dump_manager_bmc.hpp
- dump_manager_bmcstored.cpp
- meson.build
- meson_options.txt
- tools/dreport.d/dreport
- tools/dreport.d/ibm.d/gendumpheader
- tools/dreport.d/ibm.d/gendumpinfo
- tools/dreport.d/ibm.d/package
- tools/dreport.d/include.d/dcommon
Gerrit links:-
Configuration change in dump:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52116
Script changes:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52153
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52151
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52224
> Dump name change

- bmcstored_dump_entry.cpp
- dump-extensions/openpower-dumps/dump_manager_system.cpp
- dump-extensions/openpower-dumps/resource_dump_entry.cpp
- dump-extensions/openpower-dumps/system_dump_entry.cpp
- dump_utils.cpp
- dump_utils.hpp
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52227 Allow initiating mp reboot dump in quiesced state
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52260 Prevent dump delete while offloading
> Host dump fixes - offload and create 

- tools/dreport.d/ibm.d/gendumpheader
Gerrit Link: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52436
> dreport: Adding default value to model & serial number

- tools/dreport.d/openpower.d/plugins.d/dumpfilelist
- tools/dreport.d/openpower.d/plugins.d/guardlist
- tools/dreport.d/openpower.d/plugins.d/obmcconsole1
- tools/dreport.d/openpower.d/plugins.d/phal_devtree
- tools/dreport.d/plugins.d/fanctldump
- tools/dreport.d/plugins.d/hwmon
- tools/dreport.d/plugins.d/network
- tools/dreport.d/plugins.d/procfd
- tools/dreport.d/plugins.d/servicestatus
- tools/dreport.d/plugins.d/timedate
Follow commits are pulled from master
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52299/7
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52317/9
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52368/11
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52369/12
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52370/13
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52440/10
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52441/10
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52468/12
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52469/11 …
> Extend openbmc dump scripts to cater additional details to aid in debug

- bmc_dump_entry.hpp
- bmcstored_dump_entry.hpp
- dump-extensions/openpower-dumps/host_dump_entry.hpp
- dump-extensions/openpower-dumps/resource_dump_entry.hpp
- dump-extensions/openpower-dumps/system_dump_entry.hpp
- dump_entry.hpp
- dump_manager.hpp
- dump_manager_main.cpp
commits
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52573/3
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/52572/3
> object: don't use 'bool' argument constructor

- tools/dreport.d/ibm.d/gendumpheader
Gerrit link:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/53369
> opdreport: Adding file header size

- tools/dreport.d/openpower.d/plugins.d/cfam
- tools/dreport.d/openpower.d/plugins.d/dumpfilelist
- tools/dreport.d/openpower.d/plugins.d/occ
- tools/dreport.d/openpower.d/plugins.d/phal_devtree
- tools/dreport.d/plugins.d/bios
- tools/dreport.d/plugins.d/bmcweb
- tools/dreport.d/plugins.d/journalpretty
- tools/dreport.d/plugins.d/procfd
- tools/dreport.d/plugins.d/settings
Additional dump plugins to be added to BMC dump generation
CQ: SW550084
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/53284
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/53285
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/53291
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/53292
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/53293
> Additional plugins to capture debug data to BMC dump

- dump_manager_bmcstored.cpp
Gerrit link:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/53580
> dump-manager: Fixing leak in bmc dump

- bmc_dump_entry.hpp
- bmcstored_dump_entry.cpp
- bmcstored_dump_entry.hpp
- dump-extensions/openpower-dumps/dump_manager_hostdump.hpp
- dump-extensions/openpower-dumps/host_dump_entry.hpp
- dump-extensions/openpower-dumps/resource_dump_entry.hpp
- dump-extensions/openpower-dumps/system_dump_entry.hpp
- meson_options.txt
Changes
60923: OpenPOWER: Remove duplicate OriginatedBy interface | https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/60923
https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/42932/40..41
https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/41117/63..64
> Fixes for system dump and BMC dump 

- dump_manager_bmcstored.cpp
There is a merge issue with the size calculation, fixing it.
https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/61378
Change-Id: Ic7bea4dfddf2f832526da48e301e81dea190a860
> Fix the size calculation

- dump-extensions/openpower-dumps/dump-extensions.cpp
- dump-extensions/openpower-dumps/dump_manager_resource.cpp
- dump-extensions/openpower-dumps/dump_manager_resource.hpp
- dump-extensions/openpower-dumps/dump_manager_system.cpp
- dump-extensions/openpower-dumps/dump_manager_system.hpp
- dump-extensions/openpower-dumps/meson.build
- dump-extensions/openpower-dumps/resource_dump_entry.cpp
- dump-extensions/openpower-dumps/resource_dump_entry.hpp
- dump-extensions/openpower-dumps/resource_dump_serialize.cpp
- dump-extensions/openpower-dumps/resource_dump_serialize.hpp
- dump-extensions/openpower-dumps/system_dump_entry.cpp
- dump-extensions/openpower-dumps/system_dump_entry.hpp
- dump-extensions/openpower-dumps/system_dump_serialize.cpp
- dump-extensions/openpower-dumps/system_dump_serialize.hpp
- meson_options.txt
Gerrit links:  
https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/47088/21  
https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/47234/10  
https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/51513/5
> Serialize dumps

- .shellcheck-ignore
- tools/dreport.d/ibm.d/plugins.d/badpel
- tools/dreport.d/openpower.d/plugins.d/hostboot
> dreport: Adding badpel and hostboot scripts

- .clang-format
- core_manager.cpp
- dump-extensions/openpower-dumps/dump_manager_hostdump.hpp
- dump-extensions/openpower-dumps/dump_manager_system.cpp
- dump-extensions/openpower-dumps/op_dump_util.cpp
- dump-extensions/openpower-dumps/system_dump_entry.cpp
- dump_manager_bmcstored.cpp
- dump_offload.cpp
- dump_utils.cpp
- dump_utils.hpp
- elog_watch.cpp
- host-transport-extensions/pldm/common/pldm_utils.cpp
- meson.build
- ramoops_manager.cpp
- test/debug_inif_test.cpp
- watch.cpp
Pulls in a couple of upstream commits + the needed changes for our downstream code to work with clang16.
> 1050 clang16

- dump_manager_bmc.cpp
If dump manager crashes core file will be generated but core dump will not be created as the dump service that creates core dump is taking a reset. Wee check for core files at the start of the dump service and capture them in core dump.
During this scenario, if there is any exception with capturing the dump, it was not handled.
Fix:
Added exception handling for the above scenario.
> Handle exceptions thrown during checkAndInitialize

- tools/dreport.d/plugins.d/journalpretty
```
Change-Id: I70c52a5ce1487ed01ac934da790c5d7a352535cb
Signed-off-by: Marri Devender Rao <devenrao@in.ibm.com>
Co-authored-by: Marri Devender Rao <devenrao@in.ibm.com>```
> 1050: Modify plugin to capture all journal data during elog/core dump (#134)

- tools/dreport.d/openpower.d/opdreport
There is an issue in the variable assignment line while fixing >80 like reverting the changes
> Fix the variable assignment

- dump-extensions/openpower-dumps/dump_entry_factory.hpp
- dump-extensions/openpower-dumps/dump_manager_openpower.cpp
- dump-extensions/openpower-dumps/dump_manager_openpower.hpp
- dump_manager.hpp
- watch.cpp
Change-Id: I964ccab3a5e04b364fd5965acb4bc3ac612caef5
> OpenPOWER: Handle Invalid Dump Entries

- dump-extensions/openpower-dumps/dump_entry_factory.cpp
Change-Id: I47a97cda7f09ad3310af86974f4c010a1effb765
> openPowerDumps: Do not create dump if dump policy is disabled.

- bmc_dump_entry.hpp
- bmcstored_dump_entry.cpp
- dump_offload_main.cpp
- dump_utils.hpp
- meson.build
- meson_options.txt
Test Results:
Feb 18 10:56:42 p10bmc bmcweb[2074]: (2025-02-18 10:56:42) [CRITICAL "dump_offload.hpp":445] INFO:Request open for system dump offload withurl: /redfish/v1/Systems/system/LogServices/Dump/Entries/ SBE_30000003/attachment
Feb 18 10:56:42 p10bmc bmcweb[2074]: (2025-02-18 10:56:42) [CRITICAL "dump_offload.hpp":499] INFO: sbe dump id 30000003 offload initiated by: 10.231.201.31
Feb 18 10:56:42 p10bmc phosphor-dump-manager[5616]: offload started id(30000003) uri(/tmp/DumpOffloadSockets/sbe_dump_714) Feb 18 10:56:43 p10bmc phosphor-offload-handler[5617]: Opening File for RW, FILENAME(SYSDUMP.139EF60.30000003.20250218105515) Feb 18 10:56:43 p10bmc phosphor-dump-manager[5616]: Dump offload completed id(30000003)
Feb 18 10:56:43 p10bmc bmcweb[2074]: (2025-02-18 10:56:43) [CRITICAL …
> Create PEL when a dump is offloaded
